/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type CodeBlock = {
  _type: "codeBlock";
  language?: string;
  code?: string;
};

export type Callout = {
  _type: "callout";
  tone?: "info" | "warning";
  text?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  noindex?: boolean;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  entityType?: "person" | "organization";
  entityName?: string;
  navigation?: Array<{
    label?: string;
    href?: string;
    _type: "navItem";
    _key: string;
  }>;
  social?: Array<{
    label?: string;
    url?: string;
    _type: "socialLink";
    _key: string;
  }>;
  footerText?: string;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  excerpt?: string;
  image?: ImageWithAlt;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & ImageWithAlt)
    | ({
        _key: string;
      } & Callout)
    | ({
        _key: string;
      } & CodeBlock)
  >;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & ImageWithAlt)
    | ({
        _key: string;
      } & Callout)
    | ({
        _key: string;
      } & CodeBlock)
  >;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | CodeBlock
  | Callout
  | SanityImageAssetReference
  | ImageWithAlt
  | Seo
  | SiteSettings
  | Post
  | Slug
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/lib/sanity/queries.ts
// Variable: imageFields
// Query: {  _type, alt, caption, hotspot, crop,  "asset": asset->{ _id, url, metadata { dimensions { width, height }, lqip } }}
export type ImageFieldsResult = {
  _type: never;
  alt: never;
  caption: never;
  hotspot: never;
  crop: never;
  asset: never;
};

// Source: ../src/lib/sanity/queries.ts
// Variable: siteSettingsQuery
// Query: *[_id == "siteSettings"][0]{  title, description, entityType, entityName, footerText,  navigation[]{ label, href },  social[]{ label, url }}
export type SiteSettingsQueryResult =
  | {
      title: string | null;
      description: null;
      entityType: null;
      entityName: null;
      footerText: null;
      navigation: null;
      social: null;
    }
  | {
      title: string | null;
      description: string | null;
      entityType: null;
      entityName: null;
      footerText: null;
      navigation: null;
      social: null;
    }
  | {
      title: string | null;
      description: string | null;
      entityType: "organization" | "person" | null;
      entityName: string | null;
      footerText: string | null;
      navigation: Array<{
        label: string | null;
        href: string | null;
      }> | null;
      social: Array<{
        label: string | null;
        url: string | null;
      }> | null;
    }
  | null;

// Source: ../src/lib/sanity/queries.ts
// Variable: pagesQuery
// Query: *[_type == "page" && defined(slug.current)] | order(title asc){  _id, title, "slug": slug.current, excerpt, _updatedAt}
export type PagesQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  _updatedAt: string;
}>;

// Source: ../src/lib/sanity/queries.ts
// Variable: pageSlugsQuery
// Query: *[_type == "page" && defined(slug.current)]{ _id, "slug": slug.current }
export type PageSlugsQueryResult = Array<{
  _id: string;
  slug: string | null;
}>;

// Source: ../src/lib/sanity/queries.ts
// Variable: pageBySlugQuery
// Query: *[_type == "page" && slug.current == $slug][0]{  _id, _updatedAt, title, "slug": slug.current, excerpt,  body[]{ ..., _type == "imageWithAlt" => {  _type, alt, caption, hotspot, crop,  "asset": asset->{ _id, url, metadata { dimensions { width, height }, lqip } }} },  seo}
export type PageBySlugQueryResult = {
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "callout";
        tone?: "info" | "warning";
        text?: string;
      }
    | {
        _key: string;
        _type: "codeBlock";
        language?: string;
        code?: string;
      }
    | {
        _key: string;
        _type: "imageWithAlt";
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            dimensions: {
              width: number | null;
              height: number | null;
            } | null;
            lqip: string | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string | null;
        caption: string | null;
      }
  > | null;
  seo: Seo | null;
} | null;

// Source: ../src/lib/sanity/queries.ts
// Variable: postsQuery
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc){  _id, title, "slug": slug.current, excerpt, publishedAt, _updatedAt,  "image": image{  _type, alt, caption, hotspot, crop,  "asset": asset->{ _id, url, metadata { dimensions { width, height }, lqip } }}}
export type PostsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  _updatedAt: string;
  image: {
    _type: "imageWithAlt";
    alt: string | null;
    caption: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
        lqip: string | null;
      } | null;
    } | null;
  } | null;
}>;

// Source: ../src/lib/sanity/queries.ts
// Variable: postBySlugQuery
// Query: *[_type == "post" && slug.current == $slug][0]{  _id, _updatedAt, title, "slug": slug.current, excerpt, publishedAt,  "image": image{  _type, alt, caption, hotspot, crop,  "asset": asset->{ _id, url, metadata { dimensions { width, height }, lqip } }},  body[]{ ..., _type == "imageWithAlt" => {  _type, alt, caption, hotspot, crop,  "asset": asset->{ _id, url, metadata { dimensions { width, height }, lqip } }} },  seo}
export type PostBySlugQueryResult = {
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  image: {
    _type: "imageWithAlt";
    alt: string | null;
    caption: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
        lqip: string | null;
      } | null;
    } | null;
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "callout";
        tone?: "info" | "warning";
        text?: string;
      }
    | {
        _key: string;
        _type: "codeBlock";
        language?: string;
        code?: string;
      }
    | {
        _key: string;
        _type: "imageWithAlt";
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            dimensions: {
              width: number | null;
              height: number | null;
            } | null;
            lqip: string | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string | null;
        caption: string | null;
      }
  > | null;
  seo: Seo | null;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '{\n  _type, alt, caption, hotspot, crop,\n  "asset": asset->{ _id, url, metadata { dimensions { width, height }, lqip } }\n}': ImageFieldsResult;
    '*[_id == "siteSettings"][0]{\n  title, description, entityType, entityName, footerText,\n  navigation[]{ label, href },\n  social[]{ label, url }\n}': SiteSettingsQueryResult;
    '*[_type == "page" && defined(slug.current)] | order(title asc){\n  _id, title, "slug": slug.current, excerpt, _updatedAt\n}': PagesQueryResult;
    '*[_type == "page" && defined(slug.current)]{ _id, "slug": slug.current }': PageSlugsQueryResult;
    '*[_type == "page" && slug.current == $slug][0]{\n  _id, _updatedAt, title, "slug": slug.current, excerpt,\n  body[]{ ..., _type == "imageWithAlt" => {\n  _type, alt, caption, hotspot, crop,\n  "asset": asset->{ _id, url, metadata { dimensions { width, height }, lqip } }\n} },\n  seo\n}': PageBySlugQueryResult;
    '*[_type == "post" && defined(slug.current)] | order(publishedAt desc){\n  _id, title, "slug": slug.current, excerpt, publishedAt, _updatedAt,\n  "image": image{\n  _type, alt, caption, hotspot, crop,\n  "asset": asset->{ _id, url, metadata { dimensions { width, height }, lqip } }\n}\n}': PostsQueryResult;
    '*[_type == "post" && slug.current == $slug][0]{\n  _id, _updatedAt, title, "slug": slug.current, excerpt, publishedAt,\n  "image": image{\n  _type, alt, caption, hotspot, crop,\n  "asset": asset->{ _id, url, metadata { dimensions { width, height }, lqip } }\n},\n  body[]{ ..., _type == "imageWithAlt" => {\n  _type, alt, caption, hotspot, crop,\n  "asset": asset->{ _id, url, metadata { dimensions { width, height }, lqip } }\n} },\n  seo\n}': PostBySlugQueryResult;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
